# Generated by Django 4.1.4 on 2022-12-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('01', 'Class I'), ('02', 'Class II'), ('03', 'Class III'), ('04', 'Class IV'), ('05', 'Class V'), ('06', 'Class VI'), ('07', 'Class VII'), ('08', 'Class VIII'), ('09', 'Class IX'), ('10', 'Class X'), ('11', 'Class XI'), ('12', 'Class XII')], max_length=2),
        ),
    ]
