# Generated by Django 4.1.4 on 2022-12-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default='2022-07-07'),
            preserve_default=False,
        ),
    ]
